pull_request_template.md
=> Pull request 템플릿을 추가

src/app/(home)/page.tsx, src/app/globals.css, src/app/layout.tsx, src/app/page.tsx
- 모바일 width 지정
- global css, home page 추가
=> 💄 style: 모바일 width 지정

src/app/(home)/page.tsx, src/utils/supabase/server.ts
- supabase server 파일 생성
- utils/supabase/server.ts에서 createClient import 해서 쓰시면 수파베이스 로직 사용 가능합니다 여러부운~
=> 🎉 add: supabase server 파일 생성

src/app/mypage/page.tsx, src/app/mypage/written/page.tsx, src/utils/supabase/supabaseClient.ts
-마이페이지 UI 구현 및 관련 페이지 라우팅 추가.
마이페이지 메인 UI 구현 (mypage/page.tsx).
(프로필 섹션, 크레딧 섹션, 셀러 인증, 활동 내역, 설정 UI)
내가 작성한 게시물 페이지 추가 (mypage/written/page.tsx).
-
=> 🎉add:마이페이지 UI

src/app/(home)/_components/PostList.tsx
-  feat: 게시물 페이지네이션(더보기)
-  use infinite query
=> ✨ feat: 게시물 페이지네이션(더보기)

src/app/(home)/_components/PostList.tsx
- postlist pagination에서 각 항목별로 필터링시 갯수가 다르게 나오는 문제 수정
- supabase 로직에 .eq 추가
=> 🩹fix: postlist pagination

src/app/mypage/page.tsx, src/app/mypage/seller-auth/page.tsx, src/app/mypage/written/page.tsx, src/utils/supabase/middleware.ts
- 인증 페이지와 활동 내역 페이지의 UI를 작성했습니다.
- 인증 페이지 UI 구현
- 국가인증, 본인인증 버튼 추가
- 인증 카드 스타일 및 레이아웃 작성
- 활동 내역 페이지 UI 구현
- 프로필 섹션 추가
- 작성한 글, 구매한 글, 북마크 카테고리 버튼 UI 작성
- 카드 리스트 스타일링
-
=> 💄 style:인증, 활동내역 UI

src/app/(home)/_components/PostList.tsx
- 메인 페이지에서 각 게시물별 북마크 기능 추가
- 메인 페이지에서 각 게시물별 북마크 기능 추가
=> ✨ feat: 북마크 기능 추가

src/app/auth/callback/route.ts, src/app/login/action.ts, src/app/login/page.tsx, src/utils/supabase/client.ts
- 구글, 카카오 양 쪽의 oauth 기능의 구현 완료
- oauth 기능 완료.
-  route.ts가 제대로 작동하지 않아, 사용자를 이상한 url로 리다이렉트 시키는 문제를 수정하였습니다.
=> ✨ feat : 카카오 로그인 기능의 구현 완료

src/app/mypage/bookmark/page.tsx, src/app/mypage/language/page.tsx, src/app/mypage/page.tsx, src/app/mypage/seller-auth/page.tsx, src/app/mypage/written/page.tsx
=> 💄 style:언어설정 페이지UI

package.json, src/app/layout.tsx, src/app/login/action.ts, src/app/login/layout.tsx, src/app/providers.tsx, src/app/search/page.tsx, src/components/Header.tsx, src/providers/TanstackQueryProvider.ts, yarn.lock
- 프로바이더 관련 폴더 구조의 개편
- 헤더 바, 서치 관련된 파일 추가. 
- #60
=> 🚚 chore: providers 파일 구조 변경.

pull_request_template.md, src/app/search/page.tsx
- PR 템플릿의 수정. 
- 이슈 넘버를 추가할 수 있도록 변경 
- #63
=> 🩹 fix : PR 템플릿 수정.

src/app/auth/callback/route.ts, src/app/login/action.ts, src/app/login/page.tsx, src/app/search/page.tsx
- 🩹 fix : 고장 난 로그인 기능을 고쳤습니다. ✨ feat : getUser라는 함수를 생성하였습니다.
- 로그인의 action.ts에 getUser라는 함수가 생성되었ㅅ브니다. 
`const fetchUserProfile = async () => {
const data = await getUser();
return data![0]; // 인증된 유저의 프로필 반환
};
const {
data: userProfile,
isPending,
isError,
error,
refetch,
} = useQuery({
queryKey: ['userProfile'],
queryFn: fetchUserProfile,
});
console.log(userProfile);`
- 이런 코드를 쓰면 유저 프로파일을 받아올 수 있습니다. 아래는 찍힌 콘솔 로그의 이미지입니다. 
- 탄스택을 통해서 받아오면 됩니다. 
- #68
=> 🩹 fix : 고장 난 로그인 기능을 고쳤습니다. ✨ feat : getUser라는 함수를 생성하였습니다.

src/app/(home)/_components/qnaHeader.tsx, src/app/(home)/_hooks/useDelete.ts, src/app/globals.css, src/app/post/[id]/page.tsx, src/app/post/_components/RenderTranslatedHTML.tsx, src/app/post/_hooks/usePost.ts, src/app/post/_hooks/useResPosts.ts, src/app/post/_hooks/useTranslate.ts, src/app/post/ai.tsx
- ✨ feat: 번역 기능 추가
- 상세 페이지에서 번역된 텍스트가 나오도록 까지 구현 완료하였습니다.
- 오리지널 텍스트 대신 나오도록 수정해야함
- 원문보기 버튼 추가해야함
=> ✨ feat: 번역 기능 추가

src/app/mypage/_components/CategoryTabs.tsx, src/app/mypage/page.tsx, src/app/mypage/request/page.tsx, src/app/mypage/response/page.tsx
-프로필 사진 업데이트 기능, 카테고리탭 카운트 추가
- 프로필 사진 업데이트 기능 추가:
- Supabase Storage에 이미지 업로드 및 URL 저장.
- 카테고리 탭 기능 개선:
- 작성글, 답변글, 북마크 개수가 로그인한 사용자의 데이터 기준으로 표시되도록 수정.
-
=> ✨ feat:프로필 사진 업데이트 기능, 카테고리탭 카운트 추가

src/app/(home)/[id]/page.tsx, src/app/(home)/_components/headerButton.tsx, src/app/(home)/_components/navBar.tsx, src/app/(home)/_components/qnaHeader.tsx, src/app/globals.css, src/app/post/[id]/page.tsx
- 💄style: home style
- home 화면의 메뉴 부분이 figma와 비슷하게 수정되었습니다.
- inner css를 수정하였습니다.
=> 💄style: home style

src/app/login/action.ts, src/app/search/[id]/page.tsx, src/utils/api/supabase_api/getUser.ts
- 🚚 chore : 파일 구조 변경
- 파일 구조가 변경되었습니다. api가 이제는 app 폴더 바깥에 있습니다.
=> 🚚 chore : 파일 구조 변경

src/app/mypage/_components/CategoryTabs.tsx, src/app/mypage/_components/PostCard.tsx, src/app/mypage/request/page.tsx, src/app/mypage/response/page.tsx, src/app/mypage/seller-auth/country-verification/page.tsx, src/app/mypage/seller-auth/identity-verification/codepage/page.tsx, src/app/mypage/seller-auth/identity-verification/page.tsx, src/app/mypage/seller-auth/page.tsx
-본인 인증 및 인증 코드 입력 페이지 추가
--국가 및 전화번호 입력 UI 추가
- 인증 코드 입력 UI 추가
- 라우팅 연결 
- 작성글, 답변글 카운트 기능 추가
-
=> ✨ feat: 본인 인증 및 인증 코드 입력 페이지 추가

src/app/mypage/page.tsx, src/app/mypage/request/page.tsx, src/app/mypage/response/page.tsx, src/app/mypage/seller-auth/identity-verification/codepage/page.tsx, src/app/mypage/seller-auth/identity-verification/page.tsx, src/app/mypage/seller-auth/page.tsx
-인증번호 발급 및 인증 절차 구현
- 인증번호 발급 및 표시 구현
- 인증번호 6자리 랜덤 생성 및 표시
- 재전송 버튼 클릭 시 새로운 인증번호 생성
- 인증 완료 후 상태 업데이트
- 인증 상태를 Supabase의 `authenticated` 필드로 업데이트
- 인증 완료 시 UI 상태 변경 (완료 마크 및 메시지 추가)
-
=> ✨feat: 인증번호 발급 및 인증 절차 구현

next.config.mjs, src/app/post/[id]/page.tsx, src/app/post/_components/BackBtn.tsx, src/app/post/_components/BookmarkBtn.tsx, src/app/post/_components/Responses.tsx, src/app/post/_hooks/useResPosts.ts, src/app/post/_hooks/useTranslate.ts, src/utils/api/supabase_api/getUser.ts, src/utils/api/supabase_api/post/getPostUser.ts
- ♻️refactor: ssg로 변경/🔨 script: config
- post page
- config.mjs 파일에 이미지 보안 링크 추가
=> ♻️refactor: ssg로 변경/🔨 script: config

src/app/(home)/[id]/page.tsx, src/app/(home)/_components/navBar.tsx
- ✨ feat: 최신/질문/답변 filtering
- 메인 페이지에서 최신/질문/답변 필터링
=> ✨ feat: 최신/질문/답변 filtering

components.json, package.json, src/app/(home)/_components/navBar.tsx, src/app/(home)/page.tsx, src/app/globals.css, src/components/ui/tabs.tsx, src/lib/utils.ts, tailwind.config.ts, yarn.lock
-💄 style: shadcn 메뉴바 적용
-shadcn tabs 설치
=> 💄 style: shadcn 메뉴바 적용

src/app/mypage/page.tsx
-크레딧 링크 추가
-크레딧 섹션에 링크 추가했습니다.
-
=> ✨ feat:크레딧 링크 추가

src/app/(home)/page.tsx, src/utils/api/tanstack/home/BookmarkHooks.ts, src/utils/api/tanstack/home/useBookmark.ts
- 🐛 fix: bookmark userId 오류, 비로그인 시 북마크버튼 클릭 시 얼럿
- bookmark userId 오류
- 비로그인 시 북마크버튼 클릭 시 얼럿
- #110
=> 🐛 fix: bookmark userId 오류, 비로그인 시 북마크버튼 클릭 시 얼럿

.eslintrc.json, src/app/(home)/page.tsx, src/utils/api/supabase_api/home/fetchBookmarks.ts, src/utils/api/tanstack/home/BookmarkHooks.ts, src/utils/api/tanstack/home/useBookmark.ts, src/utils/api/tanstack/home/usePosts.ts
- home에서 read 기능 수정, 기타 chores
- supabase joinquery로 질문글 카테고리 가져오기/답변글에 print
- fetch post, bookmark 함수 타입지정
- eslint에 '_'에 대한 규칙 추가
- #116
=> ✨feat: 홈 read / 🐛fix: type

src/app/login/action.ts, src/app/login/page.tsx, src/app/search/[id]/_types/searchTypes.ts, src/app/search/[id]/page.tsx, src/app/search/_components/DetailedSearchBar.tsx, src/app/search/_components/SearchResultComponent.tsx, src/app/search/_components/SearchResultCount.tsx, src/app/search/_components/SearchResults.tsx, src/app/search/_components/SelectBox.tsx, src/data/category.ts, src/utils/topics.ts
- 코드의 리팩토링 및 타입에러의 수정. 
- 서치 페이지에서 질문/답변 필터링 기능 추가. 
- 스타일을 최대한 시안과 비슷하게 수정. 
- data의 토픽들을 이모지 있는 걸로 바꾼 다음, 다시 잘 작동하나 봐야할 거 같습니다.
=> ♻️ refactor : 컴포넌트 분리 및, 타입 에러의 수정.

src/utils/topics.ts
- topic의 맵핑 데이터를 수정하여 이모지를 집어넣었습니다.
=> 💄 style : topicdata에 이모지를 추가.

src/app/mypage/bookmark/page.tsx
-북마크 기능 추가
- 북마크 기능 추가했습니다
-북마크 기능 아직 미완성인데 충돌날까봐 작업 중에 올렸습니다.
=> ✨feat:북마크 기능 추가

src/app/(home)/_components/LocationModal.tsx, src/app/(home)/_components/navBar.tsx, src/app/mypage/page.tsx, src/store/userStore.ts, src/utils/api/tanstack/home/usePosts.ts
- ✨feat: 홈 페이지에서 모달 추가/♻️refactor: 로그아웃 주스탠드
- 홈 페이지에서 나라 선택 모달 추가했습니다.
- useUserStore에 signout 로직 추가했고, mypage에서 로직 변경했습니다.
- 전역 상태 user가 잘 업데이트되는지 확인
=> ✨feat: 홈 페이지에서 모달 추가/♻️refactor: 로그아웃 주스탠드

package.json, src/app/(home)/_components/LocationModal.tsx, src/app/post/GPTTranslator.tsx, src/types/supabase.ts, yarn.lock
- script: genTypes 실행을 위한 supabase 설치
- supabase 설치
- home>모달 css 수정
- GPT translator text:text -> text
=> 🔨 script: genTypes 실행을 위한 supabase 설치

src/app/(home)/_components/LocationModal.tsx, src/app/(home)/_components/navBar.tsx, src/app/(home)/page.tsx
- ✨ feat: 나라 선택 모달
- session 스토리지에 저장
- 검색바 구현
- 선택했을때 css 등 css 수정 필요
- 검색바에서 국가 검색 구현 필요
=> ✨ feat: 나라 선택 모달

src/app/(home)/_components/LocationModal.tsx, src/app/(home)/_components/navBar.tsx, src/app/(home)/page.tsx
- 🐛 fix: 모달 기능 구현 수정
- 모달 기능에서 hydration 문제, session storage 에러를 수정하였다.
=> 🐛 fix: 모달 기능 구현 수정

src/app/mypage/_components/CategoryTabs.tsx, src/app/mypage/_components/PostCard.tsx, src/app/mypage/bookmark/page.tsx, src/app/mypage/purchase/page.tsx, src/app/mypage/request/filters/AllPosts.tsx, src/app/mypage/request/filters/Answers.tsx, src/app/mypage/request/filters/Questions.tsx, src/app/mypage/request/page.tsx
-구매글 기능 추가
-purchased_posts 테이블 데이터를 기반으로 한 구매글 목록 조회 기능 추가.
-CategoryTabs에서 구매글 카운트 연동.
-구매글 필터 및 북마크 필터와의 코드 구조 통일성 확보.
-상세 페이지 이동 및 UI 개선.
-
=> ✨feat: 구매글 기능 추가

src/app/search/_components/RequestDetail.tsx, src/app/search/_components/SearchResults.tsx, src/app/search/_components/TimeAgo.tsx, src/utils/api/supabase_api/search/getResponseCount.ts, src/utils/api/tanstack/search/useResponseCounts.ts
- 스타일 로직이 추가되었습닌다. 
- 시안과 동일하게 며칠 전에 글이 올라왔는 지를 볼 수 있습니다. 답변 단 사람의 숫자도 볼 수 있습니다. 
- 이제, response 쪽의 스타일링 및 서치와 검색 페이지 정도 남은 거 같습니다.
=> 💄 style : 경과 시간 표시 및, 답변 단 사람 인수 표시

public/images/ic-bookmark.svg, src/app/search/_components/RequestDetail.tsx, src/app/search/_components/ResponseContent.tsx, src/app/search/_components/ResponseDetail.tsx, src/app/search/_components/SearchResultCount.tsx, src/app/search/_components/SearchResults.tsx, src/app/search/_components/SelectBox.tsx, src/utils/api/supabase_api/search/getCredit.ts, src/utils/api/supabase_api/search/getResponseCount.ts, src/utils/api/tanstack/search/useCredit.tsx, src/utils/api/tanstack/search/useResponseCounts.ts
- 디자이너분에게 지적받은 부분을 고쳤습니다. 
- 댓글 숫자를 불러올 수 있게 하고, 컴포넌트를 분리하여 리팩토링을 완료하였습니다. 
- 검색 페이지, 검색바, 헤더 부분의 스타일을 이제 수정할 차례인 거 같습니다.
=> 💄style : 디자이너분 q/a 바탕으로 지적받은 부분 수정 및 댓글 숫자 기능 추가.

src/app/globals.css, src/app/mypage/_components/PostCard.tsx, src/app/request-edit/[request_id]/page.tsx, src/app/request/_components/FormFields.tsx, src/app/request/_components/TopicSelector.tsx, src/app/request/page.tsx, src/app/response-edit/[responseId]/page.tsx
- 마이페이지 내 게시글에서 수정하기 버튼을 edit 페이지들과 연결해줌
- 위와 동일
-
=> 📌 link : 수정하기 버튼 edit 페이지와 연결

src/components/LocationModalNew.tsx, src/data/images/radio_btn.svg, src/data/images/radio_btn_slctd.svg
=> 💄 style: modal 검색 시 리스트 수정정

src/app/search/[id]/_components/RequestDetail.tsx, src/app/search/_components/RecentSearchList.tsx, src/app/search/_hooks/useSearchHandlers.tsx, src/app/search/page.tsx
- 버그 수정입니다. 
- 따로 훅으로 뺐던 검색 핸들러들이 파업해서, 손을 좀 봤습니다. 이제 정상적으로 작동합니다. 
- 나라명이 제대로 표시 안 됐던 문제를 손봤습니다.
=> 🚑 fix : 최근 검색어 저장 안 되는 현상을 해결. 나라명이 제대로 표시되게 변경.

src/app/post/[id]/page.tsx, src/app/post/_components/Responses.tsx, src/components/LocationModalNew.tsx
- 💄 style: location modal
- db 변경 후 나라 이름 나오는 로직 추가
- 로케이션 모달 수정
=> 💄 style: location modal

package-lock.json, package.json, src/app/(home)/_components/navBar.tsx, src/app/(home)/page.tsx, src/app/layout.tsx, src/app/mypage/language/page.tsx, src/app/request/_api/route.ts, src/app/search/[id]/_types/searchTypes.ts, src/store/userStore.ts, src/utils/api/supabase_api/home/fetchBookmarks.ts, src/utils/api/supabase_api/home/useDelete.ts, src/utils/api/tanstack/home/BookmarkHooks.ts, src/utils/api/tanstack/search/useInfiniteSearchRequestPosts.tsx, yarn.lock
- 빌드를 시도 중에 잡은 에러들을 해결하는 중의 pr
- 빌드 오류를 '대부분' 해결
- 홈에서의 page generate 문제 미해결
=> ✨ feat : 빌드 시도 중

src/app/mypage/page.tsx, src/components/Header.tsx
- 마이 페이지의 스타일을 시안과 거의 같게 했습니다. 
- 일단은 스타일만 변경하였습니다. 
- 로그아웃 버튼 쪽이 아직 미완성입니다. 
=> 💄 style : 마이페이지 스타일을 시안과 거의 같게

src/app/post/[id]/page.tsx, src/app/response-list/_components/postCard.tsx, src/app/response-list/page.tsx, src/components/backHeader.tsx
=> 💄 style: response-list 초안

src/app/mypage/_components/FilterTabs.tsx, src/app/mypage/filters/all/page.tsx
-필터링된 게시물 렌더링 및 중복 제거 로직 수정
- 전체, 질문, 답변 게시물 필터링 기능 통합
- 로딩 및 오류 상태 처리 추가
- 게시물 필터링 후 조건에 맞는 게시물만 렌더링
-
=> 🐛fix: 필터링된 게시물 렌더링 및 중복 제거 로직 수정

src/app/mypage/seller-auth/_components/button.tsx, src/app/mypage/seller-auth/_components/locationText.tsx, src/app/mypage/seller-auth/_components/sellerAuthCard.tsx, src/app/mypage/seller-auth/country-verification/page.tsx, src/app/mypage/seller-auth/page.tsx, src/app/post/_components/BackBtn.tsx, src/components/Header.tsx
- 💄 style: seller-auth, country-verification css
=> 💄 style: seller-auth, country-verification css

src/app/mypage/seller-auth/_components/sellerAuthCard.tsx, src/app/post/_components/MapComponent2.tsx
=> 💄 style: googlemap

src/app/mypage/_components/RequestPostCard.tsx, src/app/mypage/_components/ResponsePostCard.tsx, src/app/mypage/page.tsx
-상세페이지 이동 기능 추가
-닉네임 길이에 따른 국가정보 스타일변화 고치고 상세페이지 이동 기능 추가했습니다.
-
=> ✨feat:상세페이지 이동 기능 추가

src/app/mypage/page.tsx, src/components/loginModal.tsx
=> 💄 style : login modal

src/app/mypage/_components/CategoryTabs.tsx, src/app/mypage/page.tsx, src/app/mypage/seller-auth/country-verification/page.tsx, src/app/mypage/seller-auth/page.tsx
=> 💄 style:마이페이지 스타일 변경

src/app/post/_components/Responses.tsx
=> 🩹 fix: 번역데이터 로딩전 오류

src/app/mypage/page.tsx
=> 💄style:충전하기 버튼추가

src/app/home/_components/categoryPage.tsx
=> 🩹 fix: 홈 카테고리 오류 부분 주석 처리

src/app/home/_components/categoryPage.tsx
=> 🩹 fix: 카테고리 주석처리 원복복

src/app/request-edit/[request_id]/page.tsx, src/app/request/_components/TopicSelector.tsx, src/app/request/page.tsx, src/app/review/[response_id]/_components/TimeAgo.tsx, src/app/review/[response_id]/page.tsx
- 질문글 수정 페이지 아직 공사중
- credit 페이지 리팩토링
-리팩토링 : useEffect -> tanstack Query로 변경
-
=> Feature/crud request review 페이지

src/app/post/_components/Response.tsx, src/app/post/_components/profile.tsx, src/components/Header.tsx
- ✨ feat: 원문 보기
- ✨ feat: 유저 프로필 조회
- 원문 보기 버튼을 누르면 기존 언어로 보여짐
- 유저 프로필 클릭시 마이페이지 or 유저 프로필로 이동
- #198
=> ✨ feat: 원문 보기

tailwind.config.ts
- 🚑 chore: color 지정
- 컬러팔레트의 컬러를 변수로 지정
=> 🚑 chore: color 지정

src/app/globals.css, src/app/search/[id]/_components/DetailedSearchBar.tsx, src/app/search/[id]/_components/RequestDetail.tsx, src/app/search/[id]/_components/SearchResultComponent.tsx, src/app/search/[id]/page.tsx, src/app/search/_components/RecentSearchList.tsx, src/app/search/_components/TabDetail.tsx, src/app/search/page.tsx, src/app/user/[id]/page.tsx, src/utils/api/supabase_api/user/fetchResponse.ts, src/utils/api/tanstack/user/useInfiniteUserResponsePosts.ts, yarn.lock
- 스타일 관련 pr 입니다. 
- 검색 페이지 샤드 cn으로 바꿈.
- 유저 페이지 유지 보수 중입니다. 현재, response를 받아오는 건 성공했슴다. 
- 탭이 pc에서는 어떻게 움직여야할 지를 좀 고민해봐야할 거 같습니다.
=> 💄 style : 검색 페이지에 샤드 cn으로 바꿈.

src/app/home/_components/categoryPage.tsx, src/app/home/_types/homeTypes.ts, src/components/listReqPost.tsx, src/components/listResPost.tsx, src/hook/home/RenderonlyTextHTML.tsx, src/utils/api/supabase_api/home/fetchPosts.ts
- 🩹 fix: reqposts 번역 및 기타데이터 보이게
=> 🩹 fix: reqposts 번역 및 기타데이터 보이게

src/app/mypage/_components/CategoryTabs.tsx, src/app/mypage/_components/RequestPostCard.tsx, src/app/mypage/_components/ResponsePostCard.tsx, src/app/mypage/bookmark/page.tsx, src/app/mypage/filters/all/page.tsx
-댓글 수 기능추가
-댓글 수 불러오기 기능추가
-bookmark 스타일 변경
- 
=> ✨feat:댓글 수 기능추가

src/app/mypage/_components/CategoryTabs.tsx, src/app/mypage/_components/RequestPostCard.tsx, src/app/mypage/_components/ResponsePostCard.tsx
=> ✨feat:닉네임 기능추가

public/locales/en/review.json, public/locales/en/timeAgo.json, public/locales/ko/review.json, public/locales/ko/timeAgo.json, src/app/review/[response_id]/_components/ReviewHeader.tsx, src/app/review/[response_id]/_components/ReviewInput.tsx, src/app/review/[response_id]/_components/ReviewItem.tsx, src/app/review/[response_id]/_components/ReviewList.tsx, src/app/review/[response_id]/_components/TimeAgo.tsx, src/app/review/[response_id]/_utils/review.ts, src/app/review/[response_id]/page.tsx
=> ♻️ 🌐 translation, refactor : 리뷰 페이지 언어지원 설정&리팩토링

src/app/mypage/_components/RequestPostCard.tsx, src/app/mypage/_components/ResponsePostCard.tsx, src/app/mypage/_type/type.ts, src/app/mypage/filters/all/page.tsx, src/app/mypage/purchase/page.tsx
- 🚑 fix : 카테고리가 영어로 표시되는 문제를 해결.
- 마이페이지에서 response를 불러오는 곳에서 카테고리가 영어로 표시되는 문제를 해결. 
- 제가 임의로 김민정님 코드를 건드린 거라서, 민정님 거랑 컨플릭트 가능성이 있습니다.
=> 🚑 fix : 카테고리가 영어로 표시되는 문제를 해결.

src/components/LocationModalNew.tsx, src/components/LoginModal.tsx
- 💄 style 모달 수정
- 로그인모달 나라모달 사파리에서만 보이는 문제 수정 trial
=> 💄 style 모달 수정

src/app/home/_components/CategoryPage.tsx
=> fix: 펜슬버튼 위치

src/app/mypage/_components/RequestPostCard.tsx, src/app/mypage/_components/ResponsePostCard.tsx, src/app/mypage/language/page.tsx, src/app/mypage/purchase/page.tsx
=> ✨feat:번역 기능 추가

public/locales/en/mypage.json, public/locales/ko/mypage.json, src/app/mypage/language/page.tsx
=> feat:언어설정페이지 수정

src/app/mypage/page.tsx
=> 🚑fix:프로필 모달 수정완료

public/locales/en/location.json, public/locales/ko/location.json, src/app/post/_components/ResponseBtn.tsx, src/app/response-list/page.tsx, src/components/LocationModalNew.tsx
=> 🐛 fix: 경로 이동 수정

src/app/post/_components/ResponseBtn.tsx
=> 라우터 임포트 수정

src/app/response/_components/MenuBar.tsx, src/app/response/_components/TiptapEditor.tsx
- 답변하기 페이지 UI 수정
- 답변하기 페이지 UI 수정
-
=> 💄 style : 답변하기 페이지 UI 수정

src/app/post/_components/Response.tsx, src/components/LocationModalNew.tsx, src/components/SelectBox.tsx, src/utils/api/supabase_api/home/fetchPostDelete.ts, src/utils/api/supabase_api/home/fetchResPostDelete.ts
=> 로케이션모달 길이 수정, 라우터 수정

src/app/response/_components/GoogleModal.tsx
-답변 구글 모달 UI 수정
-답변 구글 모달 최상단으로 옮기고 검색 버튼 크기 고정
-
=> 💄 style : 답변 구글 모달 UI 수정

package.json, src/app/globals.css, src/components/ListReqPost.tsx, src/components/ui/Responsive.tsx, tailwind.config.ts, yarn.lock
=> 💄 style: responsive

public/locales/en/search.json, public/locales/en/user.json, public/locales/ko/search.json, public/locales/ko/user.json, src/app/search/[id]/_components/ResponseDetail.tsx, src/app/user/_components/Header.tsx, src/app/user/_components/ProfileSection.tsx, src/app/user/_components/RequestItem.tsx, src/app/user/_components/ResponseItem.tsx, src/app/user/_components/ReviewItem.tsx, src/app/user/_components/TabNavigation.tsx, src/data/nation.ts
- ✨ feat : 검색 페이지에서 번역 덜 된 부분이 있어, 그 부분을 검수. 다른 유저 마이페이지 번역 완료.
- 다른 유저 마이페이지 번역 완료.
- 검색 부분에서 번역 누락된 부분 있길래 그 부분 번역 도로 했습니다.
=> ✨ feat : 검색 페이지에서 번역 덜 된 부분이 있어, 그 부분을 검수. 다른 유저 마이페이지 번역 완료.

package.json, src/app/mypage/_components/CategoryTabs.tsx, src/app/mypage/_components/RequestPostCard.tsx, src/app/mypage/_components/ResponsePostCard.tsx, src/app/mypage/bookmark/page.tsx, src/app/mypage/page.tsx, src/app/mypage/purchase/page.tsx, src/app/mypage/seller-auth/_components/locationText.tsx, src/app/mypage/seller-auth/country-verification/page.tsx, src/app/mypage/seller-auth/identity-verification/codepage/page.tsx, src/app/mypage/seller-auth/identity-verification/page.tsx, src/app/mypage/seller-auth/page.tsx, yarn.lock
-마이페이지 반응형 작업
- 마이페이지 반응형 작업
- 버튼이나, 언어설정 페이지는 수정중입니다
=> 마이페이지 반응형 작업

src/app/review/[response_id]/_utils/review.ts, src/app/review/[response_id]/page.tsx
-리뷰페이지 리팩토링함
-tanstack query로 바꿈
-
=> ♻️ refactor : 코드 리팩토링함

public/locales/en/search.json, public/locales/ko/search.json, src/app/search/[id]/_components/DetailedSearchBar.tsx, src/app/search/_components/SearchBar.tsx, src/providers/I18nProvider.tsx
- ✨ feat : ip 주소에 따른 언어 변경 로직 활성화. 
- 💄style : 검색 창의 스타일을 다듬음.
- 이제 접속한 ip 주소를 토대로 언어가 변경됩니다. 한국이 아니면 무조건 영어로! 
- 검색 페이지에 번역 덜 된 부분 있어서 그 점을 고쳤습니다.
=>  ✨ feat : ip 주소에 따른 언어 변경 로직 활성화. 💄style : 검색 창의 스타일을 다듬음.

src/app/home/_components/NavBar.tsx, src/app/home/_components/PostList.tsx, src/app/request-edit/[request_id]/page.tsx, src/app/request/page.tsx, src/app/response-list/page.tsx, src/components/ListReqPost.tsx, src/components/ListResPost.tsx, src/components/LocationModalNew.tsx, src/providers/ModalProvider.tsx
- ♻️ refactor: location modal 전역관리
- location modal 전역관리
- 소소한 패딩값
- 질문/답변글 리스트에서 구분 기준을 boolean 함수로 리팩터링
**- 다슬님 request, request-edit의 location modal 활용 부분이 수정되어, 충돌 예상**
=> ♻️ refactor: location modal 전역관리

package.json, src/app/home/_components/HeaderButton.tsx, src/app/home/_components/QnaHeader.tsx, src/app/home/_hooks/useAllPosts.ts, src/components/Header.tsx, src/types/supabase.ts, src/utils/api/supabase_api/home/fetchResPosts.ts, src/utils/api/tanstack/home/usePosts.ts, yarn.lock
- ♻️refactor: home/💄style: 헤더 컬러
- 수파베이스 얀으로 재설치/genTypes 실행(response translated 컬럼 추가)
- 헤더버튼 상위에서 온클릭 주도록 리팩터링
- useReqPosts, useResPosts -> usePosts로 리팩터링
- 헤더 컬러 홈 화면에서만 변경
=> ♻️refactor: home/💄style: 헤더 컬러

src/app/home/_components/HeaderButton.tsx, src/app/home/_components/NavBar.tsx, src/app/post/[id]/page.tsx, src/app/post/_components/ResponseBtn.tsx, src/app/post/_components/Responses.tsx
- style QA 수정
- 홈 질문,답변버튼 패딩값
- 홈 카테고리 라인 양끝 삐져나옴 수정
- 게시글 상세 버튼 공중부양
=> style QA 수정

public/images/ic-up&down.svg, public/locales/en/mypage.json, src/app/mypage/_components/RequestPostCard.tsx, src/app/mypage/_components/ResponsePostCard.tsx, src/app/mypage/bookmark/page.tsx, src/app/mypage/purchase/page.tsx, src/app/mypage/seller-auth/_components/locationText.tsx, src/app/mypage/seller-auth/country-verification/page.tsx, src/app/mypage/seller-auth/identity-verification/page.tsx
=> style: QA 수정

src/app/home/_types/homeTypes.ts, src/app/post/[id]/page.tsx, src/app/request/page.tsx, src/types/supabase.ts
- ✨ feat: ko, en에 따라 질문글의 언어가 달리 보이기
=> ✨ feat: ko, en에 따라 질문글의 언어가 달리 보이기

public/locales/en/mypage.json, public/locales/ko/mypage.json, src/app/mypage/_components/CategoryTabs.tsx, src/app/mypage/_components/RequestPostCard.tsx, src/app/mypage/_components/ResponsePostCard.tsx, src/app/mypage/bookmark/page.tsx, src/app/mypage/filters/all/page.tsx, src/app/mypage/language/page.tsx, src/app/mypage/page.tsx, src/app/mypage/purchase/page.tsx, src/app/mypage/seller-auth/country-verification/page.tsx
-마이페이지 QA수정
- 활동내역 상단 헤더 수정
- 삭제 모달창 구현, 알럿창 수정
- 북마크 댓글 수 기능 추가
-
=> 💄style:마이페이지 QA수정 완료

src/app/response/_components/MenuBar.tsx
- menubar bg-white 빠진거 추가
-위와 동일
-
=> 💄 style : 답변하기 menubar 디자인 수정

src/app/review/[response_id]/page.tsx
- 인풋창에 리뷰 리스트 가려져서 스크롤 생성함
- List부분 디자인만 수정
-
=> 💄 style : 리뷰페이지 스크롤 생성

src/providers/I18nProvider.tsx
-🚑 fix : cors 우회 시도.
-cors 문제 때문에 ip 주소가 제대로 판별이 안 되는 문제가 있어서, 그 부분을 수정하여 버셀 상에서 제대로 언어가 반영되게끔 하였습니다.
=> 🚑 fix : cors 우회 시도.

README.md
- ✅ add : 리드미 초안 작성.
- 리드미 초안 작성했습니다. 
- 팀원 소개 부분을 채워주세요~ 일단은 저만 넣어놨습니다.
=> ✅ add : 리드미 초안 작성.

README.md, public/locales/en/search.json, src/app/search/[id]/_components/RequestDetail.tsx, src/app/search/[id]/_components/ResponseDetail.tsx
- 번역본 일부를 소문자로 바꿨습니다.
- 리드미 일부를 수정하였습니다. 
- 대문자가 이뿐데...
=> ✏️ fix : 번역본 일부를 소문자로

public/locales/en/modal.json, public/locales/ko/modal.json, src/app/post/_components/ChargeModal.tsx, src/app/post/_components/DeleteConfirmModal.tsx, src/app/post/_components/ShareBtn.tsx, src/app/providers.tsx, src/components/SelectBox.tsx
- 모달 다국어
- 모달 다국어
- provider 주석 지움
=> feat/모달 다국어

public/locales/en/mypage.json, public/locales/ko/mypage.json, src/app/mypage/_components/CategoryTabs.tsx, src/app/mypage/_components/RequestPostCard.tsx, src/app/mypage/_components/ResponsePostCard.tsx
=> ♻️refactor:삭제 모달

src/app/mypage/_components/CategoryTabs.tsx, src/app/mypage/filters/all/page.tsx
-활동내역 오류 수정
-활동내역 오류 수정
-작성글이 없을 때에 모바일 화면이 줄어드는 부분 수정했습니다
-pc버전일 때엔 문제 없습니다.
=> 💄style:활동내역 오류 수정

src/components/DesktopLoginModal.tsx
- 🚑 fix : signup 누르면 모달 안 닫히는 현상을 수정
- 온클릭으로 클로즈 모달 넣어줬습니다.
=> 🚑 fix : signup 누르면 모달 안 닫히는 현상을 수정

src/app/home/_components/HeaderSkeleton.tsx, src/app/home/_components/Home.tsx, src/app/home/_components/HomeSkeleton.tsx, src/app/home/_components/NavBarSkeleton.tsx, src/app/home/page.tsx
- 🩹 fix: skeleton ui 수정
- 홈 화면에서 스켈레톤 ui가 2개의 헤더, 콘텐츠별로 나옴(suspense)
=> 🩹 fix: skeleton ui 수정

src/app/mypage/bookmark/page.tsx
=> fix:북마크 오류 수정

src/app/post/_components/ContentRenderer.tsx, src/app/post/_hooks/getGPTTranslator.tsx, src/app/response/[postId]/page.tsx
- response 페이지에서 request_post 의 번역본이 나오게 수정
=> response 페이지에서 request_post 의 번역본이 나오게 수정

src/components/DesktopLoginModal.tsx
- 🚑 fix : 모달창이 잘 닫히도록 route로 리팩토링
- 링크에서 라우트로 바꿨습니다.
=> 🚑 fix : 모달창이 잘 닫히도록 route로 리팩토링

public/locales/en/response.json, public/locales/ko/response.json, src/app/response/_components/GoogleModal.tsx
=> 🩹 fix : 답변하기 페이지 구글모달 언어지원 수정

src/app/post/_components/LikeBtn.tsx
=> 🩹 fix: likeBtn 로그인모달 분기

src/app/post/[id]/page.tsx
=> 🩹 fix: en->ko
